export const LANGUAGES = {
  en: {
    ui: {
      badge: "Real-life King scorekeeper",
      title: "King Scores",
      subtitle:
        "Each player chooses each mode once. The same mode can still be chosen by other players.",
      gameSetup: "Game setup",
      playersButton: "players",
      deck: "Deck",
      deal: "Deal",
      remove: "Remove",
      tricks: "Tricks",
      players: "Players",
      player: "Player",
      reset: "Reset",
      chooserProgress: "Chooser progress",
      scoreboard: "Scoreboard",
      totalScore: "Total score",
      round: "Round",
      gameFinished: "Game finished",
      allModesUsed: "All players used every mode once.",
      chooseUnusedMode: "Choose one mode this player has not used yet.",
      modes: "modes",
      alreadyUsed: "Already used by this player",
      scoring: "Scoring",
      roundTotal: "Round total",
      selected: "Selected",
      choose: "Choose",
      currentTotal: "Current total",
      required: "required",
      saveRound: "Save round",
      undoLast: "Undo last",
      roundHistory: "Round history",
      noRounds: "No rounds saved yet.",
      chooser: "Chooser",
      mode: "Mode",
      rulesReminder: "Rules reminder",
      chooserChoice: (name) => `${name}'s choice`,
      errors: {
        choosePlayer: "Choose a player first.",
        chooseOneKing: "Choose exactly one player for King of Hearts.",
        alreadyUsed: (playerName, modeName) =>
          `${playerName} already chose ${modeName}. Choose another mode.`,
        totalMustBe: (required, current) =>
          `Total must be exactly ${required}. Current total is ${current}.`,
      },
      ruleCards: [
        {
          title: "Chooser rule",
          text: "Each player can choose every mode only once. Other players can still choose the same mode.",
        },
        {
          title: "3-player rule",
          text: "In 3-player mode, use 32 cards. The chooser gets 2 extra cards and removes any 2 cards before play.",
        },
        {
          title: "Follow suit",
          text: "If the first card is diamonds and you have diamonds, you must play diamonds.",
        },
        {
          title: "Winner",
          text: "When every player has used every mode, the player with the highest score wins.",
        },
      ],
    },

    rules: {
      3: {
        cards: "32 cards: A K Q J 10 9 8 7",
        deal: "Deal 10 cards to each player and 2 extra cards to the chooser",
        remove: "Chooser removes any 2 cards from their hand before play",
        tricks: "10 tricks per round",
      },
      4: {
        cards: "32 cards: A K Q J 10 9 8 7",
        deal: "Deal 8 cards to each player",
        remove: "No cards are removed",
        tricks: "8 tricks per round",
      },
    },

    contracts: {
      3: [
        {
          id: "no-tricks",
          name: "No Tricks",
          description: "Avoid taking tricks.",
          scoringText: "Each trick = -1 point",
          maxText: "10 tricks total because chooser removes 2 cards",
          mode: "count",
          label: "Tricks taken",
          min: 0,
          max: 10,
          pointsPerUnit: -1,
        },
        {
          id: "no-hearts",
          name: "No Hearts",
          description:
            "Avoid taking hearts. Hearts cannot be led unless a player only has hearts.",
          scoringText: "Each heart = -1 point",
          maxText: "8 hearts total",
          mode: "count",
          label: "Hearts taken",
          min: 0,
          max: 8,
          pointsPerUnit: -1,
        },
        {
          id: "no-jacks",
          name: "No Jacks",
          description: "Avoid taking Jacks.",
          scoringText: "Each Jack = -4 points",
          maxText: "4 jacks total",
          mode: "count",
          label: "Jacks taken",
          min: 0,
          max: 4,
          pointsPerUnit: -4,
        },
        {
          id: "no-queens",
          name: "No Queens",
          description: "Avoid taking Queens.",
          scoringText: "Each Queen = -4 points",
          maxText: "4 queens total",
          mode: "count",
          label: "Queens taken",
          min: 0,
          max: 4,
          pointsPerUnit: -4,
        },
        {
          id: "no-last-two",
          name: "No Last Two Tricks",
          description: "Avoid taking the last two tricks.",
          scoringText: "Each of last two tricks = -8 points",
          maxText: "2 scoring tricks",
          mode: "count",
          label: "Last two tricks taken",
          min: 0,
          max: 2,
          pointsPerUnit: -8,
        },
        {
          id: "no-king-heart",
          name: "No King of Hearts",
          description:
            "Avoid taking K♥. Hearts cannot be led unless a player only has hearts.",
          scoringText: "K♥ = -16 points",
          maxText: "One card only",
          mode: "single",
          label: "Player who took K♥",
          points: -16,
        },
        {
          id: "tricks-positive",
          name: "Tricks Positive",
          description: "Take as many tricks as possible.",
          scoringText: "Each trick = +1 point",
          maxText: "10 tricks total because chooser removes 2 cards",
          mode: "count",
          label: "Tricks taken",
          min: 0,
          max: 10,
          pointsPerUnit: 1,
        },
      ],

      4: [
        {
          id: "no-tricks",
          name: "No Tricks",
          description: "Avoid taking tricks.",
          scoringText: "Each trick = -2 points",
          maxText: "8 tricks total",
          mode: "count",
          label: "Tricks taken",
          min: 0,
          max: 8,
          pointsPerUnit: -2,
        },
        {
          id: "no-hearts",
          name: "No Hearts",
          description:
            "Avoid taking hearts. Hearts cannot be led unless a player only has hearts.",
          scoringText: "Each heart = -2 points",
          maxText: "8 hearts total",
          mode: "count",
          label: "Hearts taken",
          min: 0,
          max: 8,
          pointsPerUnit: -2,
        },
        {
          id: "no-jacks",
          name: "No Jacks",
          description: "Avoid taking Jacks.",
          scoringText: "Each Jack = -4 points",
          maxText: "4 jacks total",
          mode: "count",
          label: "Jacks taken",
          min: 0,
          max: 4,
          pointsPerUnit: -4,
        },
        {
          id: "no-queens",
          name: "No Queens",
          description: "Avoid taking Queens.",
          scoringText: "Each Queen = -4 points",
          maxText: "4 queens total",
          mode: "count",
          label: "Queens taken",
          min: 0,
          max: 4,
          pointsPerUnit: -4,
        },
        {
          id: "no-last-two",
          name: "No Last Two Tricks",
          description: "Avoid taking the last two tricks.",
          scoringText: "Each of last two tricks = -8 points",
          maxText: "2 scoring tricks",
          mode: "count",
          label: "Last two tricks taken",
          min: 0,
          max: 2,
          pointsPerUnit: -8,
        },
        {
          id: "no-king-heart",
          name: "No King of Hearts",
          description:
            "Avoid taking K♥. Hearts cannot be led unless a player only has hearts.",
          scoringText: "K♥ = -16 points",
          maxText: "One card only",
          mode: "single",
          label: "Player who took K♥",
          points: -16,
        },
        {
          id: "tricks-positive",
          name: "Tricks Positive",
          description: "Take as many tricks as possible.",
          scoringText: "Each trick = +2 points",
          maxText: "8 tricks total",
          mode: "count",
          label: "Tricks taken",
          min: 0,
          max: 8,
          pointsPerUnit: 2,
        },
      ],
    },
  },

  ka: {
    ui: {
      badge: "კინგის ქულების ჩამწერი",
      title: "კინგის ქულები",
      subtitle:
        "თითო მოთამაშე თითო რეჟიმს ირჩევს მხოლოდ ერთხელ. იგივე რეჟიმი სხვა მოთამაშეს ისევ შეუძლია აირჩიოს.",
      gameSetup: "თამაშის პარამეტრები",
      playersButton: "მოთამაშე",
      deck: "კარტი",
      deal: "დარიგება",
      remove: "ამოღება",
      tricks: "აღებები",
      players: "მოთამაშეები",
      player: "მოთამაშე",
      reset: "განულება",
      chooserProgress: "არჩევის პროგრესი",
      scoreboard: "ქულების ცხრილი",
      totalScore: "ჯამური ქულა",
      round: "რაუნდი",
      gameFinished: "თამაში დასრულდა",
      allModesUsed: "ყველა მოთამაშემ ყველა რეჟიმი ერთხელ გამოიყენა.",
      chooseUnusedMode: "აირჩიე რეჟიმი, რომელიც ამ მოთამაშეს ჯერ არ აურჩევია.",
      modes: "რეჟიმი",
      alreadyUsed: "ამ მოთამაშეს უკვე გამოყენებული აქვს",
      scoring: "ქულები",
      roundTotal: "რაუნდის ჯამი",
      selected: "არჩეულია",
      choose: "არჩევა",
      currentTotal: "ახლა ჯამი",
      required: "საჭიროა",
      saveRound: "რაუნდის შენახვა",
      undoLast: "უკან დაბრუნება",
      roundHistory: "რაუნდების ისტორია",
      noRounds: "ჯერ არცერთი რაუნდი არ არის შენახული.",
      chooser: "ამრჩევი",
      mode: "რეჟიმი",
      rulesReminder: "წესების შეხსენება",
      chooserChoice: (name) => `${name} ირჩევს რეჟიმს`,
      errors: {
        choosePlayer: "ჯერ აირჩიე მოთამაშე.",
        chooseOneKing: "გულის მეფეზე ზუსტად ერთი მოთამაშე უნდა აირჩიო.",
        alreadyUsed: (playerName, modeName) =>
          `${playerName}-ს ეს რეჟიმი უკვე არჩეული აქვს. აირჩიე სხვა რეჟიმი.`,
        totalMustBe: (required, current) =>
          `ჯამური რაოდენობა უნდა იყოს ზუსტად ${required}. ახლა არის ${current}.`,
      },
      ruleCards: [
        {
          title: "არჩევის წესი",
          text: "თითო მოთამაშეს თითო რეჟიმის არჩევა მხოლოდ ერთხელ შეუძლია. სხვა მოთამაშეებს იგივე რეჟიმის არჩევა მაინც შეუძლიათ.",
        },
        {
          title: "3 მოთამაშის წესი",
          text: "3 მოთამაშეზე გამოიყენება 32 კარტი. ამრჩევი იღებს 2 ზედმეტ კარტს და თამაშის დაწყებამდე ნებისმიერ 2 კარტს აგდებს.",
        },
        {
          title: "ფერის მიყოლის წესი",
          text: "თუ პირველი კარტი არის აგური და შენ გაქვს აგური, აუცილებლად აგური უნდა ჩახვიდე.",
        },
        {
          title: "გამარჯვებული",
          text: "როცა ყველა მოთამაშე ყველა რეჟიმს გამოიყენებს, იმარჯვებს ყველაზე მაღალი ქულის მქონე მოთამაშე.",
        },
      ],
    },

    rules: {
      3: {
        cards: "32 კარტი: A K Q J 10 9 8 7",
        deal: "ყველას ურიგდება 10 კარტი, ამრჩევს ემატება 2 კარტი",
        remove:
          "ამრჩევი თავისი ხელიდან ირჩევს ნებისმიერ 2 კარტს და აგდებს თამაშიდან",
        tricks: "თითო რაუნდში 10 აღებაა",
      },
      4: {
        cards: "32 კარტი: A K Q J 10 9 8 7",
        deal: "ყველას ურიგდება 8 კარტი",
        remove: "არაფერი არ იგდება თამაშიდან",
        tricks: "თითო რაუნდში 8 აღებაა",
      },
    },

    contracts: {
      3: [
        {
          id: "no-tricks",
          name: "არ აიღო კარტები",
          description: "მიზანია არ აიღო კარტი.",
          scoringText: "თითო აღება = -1 ქულა",
          maxText: "სულ 10 აღებაა, რადგან ამრჩევი 2 კარტს აგდებს თამაშიდან",
          mode: "count",
          label: "აღებების რაოდენობა",
          min: 0,
          max: 10,
          pointsPerUnit: -1,
        },
        {
          id: "no-hearts",
          name: "არ აიღო გულები",
          description:
            "მიზანია არ აიღო გულის კარტები. გულით დაწყება არ შეიძლება, თუ ხელში სხვა ფერიც გაქვს.",
          scoringText: "თითო გული = -1 ქულა",
          maxText: "სულ 8 გულია",
          mode: "count",
          label: "აღებული გულები",
          min: 0,
          max: 8,
          pointsPerUnit: -1,
        },
        {
          id: "no-jacks",
          name: "არ აიღო ვალეტები",
          description: "მიზანია არ აიღო ვალეტები.",
          scoringText: "თითო ვალეტი = -4 ქულა",
          maxText: "სულ 4 ვალეტია",
          mode: "count",
          label: "აღებული ვალეტები",
          min: 0,
          max: 4,
          pointsPerUnit: -4,
        },
        {
          id: "no-queens",
          name: "არ აიღო დამები",
          description: "მიზანია არ აიღო დამები.",
          scoringText: "თითო დამა = -4 ქულა",
          maxText: "სულ 4 დამაა",
          mode: "count",
          label: "აღებული დამები",
          min: 0,
          max: 4,
          pointsPerUnit: -4,
        },
        {
          id: "no-last-two",
          name: "არ აიღო ბოლო ორი ",
          description: "მიზანია არ აიღო ბოლო ორი კარტი.",
          scoringText: "ბოლო ორი აღებიდან თითო = -8 ქულა",
          maxText: "ქულა იწერება მხოლოდ ბოლო 2 აღებაზე",
          mode: "count",
          label: "აღებული ბოლო ორი",
          min: 0,
          max: 2,
          pointsPerUnit: -8,
        },
        {
          id: "no-king-heart",
          name: "არ აიღო გულის კინგი",
          description:
            "მიზანია არ აიღო K♥. გულით დაწყება არ შეიძლება, თუ ხელში სხვა ფერიც გაქვს.",
          scoringText: "K♥ = -16 ქულა",
          maxText: "მხოლოდ ერთი კარტი",
          mode: "single",
          label: "ვინ აიღო K♥",
          points: -16,
        },
        {
          id: "tricks-positive",
          name: "კარტის აღება",
          description: "მიზანია რაც შეიძლება ბევრი კარტი აიღო.",
          scoringText: "თითო აღება = +1 ქულა",
          maxText: "სულ 10 აღებაა, რადგან ამრჩევი 2 კარტს აგდებს თამაშიდან",
          mode: "count",
          label: "კარტის აღების რაოდენობა",
          min: 0,
          max: 10,
          pointsPerUnit: 1,
        },
      ],

      4: [
        {
          id: "no-tricks",
          name: "არ აიღო კარტები",
          description: "მიზანია არ აიღო კარტები.",
          scoringText: "თითო აღება = -2 ქულა",
          maxText: "სულ 8 აღებაა",
          mode: "count",
          label: "კარტის აღებების რაოდენობა",
          min: 0,
          max: 8,
          pointsPerUnit: -2,
        },
        {
          id: "no-hearts",
          name: "არ აიღო გულები",
          description:
            "მიზანია არ აიღო გულის კარტები. გულით დაწყება არ შეიძლება, თუ ხელში სხვა ფერიც გაქვს.",
          scoringText: "თითო გული = -2 ქულა",
          maxText: "სულ 8 გულია",
          mode: "count",
          label: "აღებული გულები",
          min: 0,
          max: 8,
          pointsPerUnit: -2,
        },
        {
          id: "no-jacks",
          name: "არ აიღო ვალეტები",
          description: "მიზანია არ აიღო ვალეტები.",
          scoringText: "თითო ვალეტი = -4 ქულა",
          maxText: "სულ 4 ვალეტია",
          mode: "count",
          label: "აღებული ვალეტები",
          min: 0,
          max: 4,
          pointsPerUnit: -4,
        },
        {
          id: "no-queens",
          name: "არ აიღო დამები",
          description: "მიზანია არ აიღო დამები.",
          scoringText: "თითო დამა = -4 ქულა",
          maxText: "სულ 4 დამაა",
          mode: "count",
          label: "აღებული დამები",
          min: 0,
          max: 4,
          pointsPerUnit: -4,
        },
        {
          id: "no-last-two",
          name: "არ აიღო ბოლო ორი",
          description: "მიზანია არ აიღო ბოლო ორი კარტი.",
          scoringText: "ბოლო ორი აღებიდან თითო = -8 ქულა",
          maxText: "ქულა იწერება მხოლოდ ბოლო 2 აღებაზე",
          mode: "count",
          label: "აღებული ბოლო ორი",
          min: 0,
          max: 2,
          pointsPerUnit: -8,
        },
        {
          id: "no-king-heart",
          name: "არ აიღო გულის კინგი",
          description:
            "მიზანია არ აიღო K♥. გულით დაწყება არ შეიძლება, თუ ხელში სხვა ფერიც გაქვს.",
          scoringText: "K♥ = -16 ქულა",
          maxText: "მხოლოდ ერთი კარტი",
          mode: "single",
          label: "ვინ აიღო K♥",
          points: -16,
        },
        {
          id: "tricks-positive",
          name: "აღებები პლიუსში",
          description: "მიზანია რაც შეიძლება ბევრი აღება აიღო.",
          scoringText: "თითო აღება = +2 ქულა",
          maxText: "სულ 8 აღებაა",
          mode: "count",
          label: "აღებების რაოდენობა",
          min: 0,
          max: 8,
          pointsPerUnit: 2,
        },
      ],
    },
  },
};
